[project]
name = "notibday"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "docopt>=0.6.2",
    "google-api-python-client>=2.169.0",
    "oauth2client>=4.1.3",
    "prettyconf>=2.3.0",
    "telegramtk>=0.1.0",
]

[dependency-groups]
dev = ["ipython>=9.2.0", "pytest>=8.3.5"]
